name: Run workflow

on:
  push:
    branches: [ main ]
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  workflow_call:

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      ( github.event_name == 'pull_request'  && contains(github.event.pull_request.labels.*.name, 'run_workflow' ))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pyiron/actions/build-notebooks@actions-3.1.0
        with:
          python-version: '3.11'
          env-files: ./environment.yml
